name = "sg1"
main = "_workervli.js"
compatibility_date = "2023-05-26"


[[routes]] 
pattern = "shopee.co.id.sg1.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "sg1.freevpn.biz.id"
custom_domain = true


[vars]
PROXYIP = "128.199.228.44"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_NYA = "https://dns.google.com/dns-query"
