name = "my2"
main = "src/_worker-vless.js"
compatibility_date = "2023-05-26"

[[routes]] 
pattern = "shopee.co.id.my2.tebel.cfd"
zone_name = "tebel.cfd"

[[routes]]
pattern = "my2.tebel.cfd"
zone_name = "tebel.cfd"

[[routes]] 
pattern = "shopee.co.id.my2.tebel.cfd"
custom_domain = true

[[routes]]
pattern = "my2.tebel.cfd"
custom_domain = true


[vars]
PROXYIP = "103.161.133.155"
DNS_NYA = "https://dns.adguard.com/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
