name = "my1"
main = "_workervl.js"
compatibility_date = "2024-05-13"

[[routes]]
pattern = "my1.porfuse.cfd"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.my1.porfuse.cfd"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.my1.porfuse.cfd"
custom_domain = true


[vars]
PROXYIP = "103.75.188.126"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
