name = "my3"
main = "_workervli.js"
compatibility_date = "2023-05-26"





[vars]
PROXYIP = "124.217.225.194"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_NYA = "https://dns.adguard.com/dns-query"
