name = "amz"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]] 
pattern = "shopee.co.id.sg4.tebel.cfd"
custom_domain = true

[[routes]]
pattern = "sg4.tebel.cfd"
custom_domain = true

[[routes]] 
pattern = "shopee.co.id.sg4.tebel.cfd"
zone_name = "tebel.cfd"

[[routes]]
pattern = "sg4.tebel.cfd"
zone_name = "tebel.cfd"



[vars]
PROXYIP = "52.74.101.26"
DNS_NYA = "https://dns.adguard.com/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
