name = "ovh"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]] 
pattern = "shopee.co.id.sg5.tebel.cfd"
custom_domain = true

[[routes]]
pattern = "sg5.tebel.cfd"
custom_domain = true

[[routes]] 
pattern = "shopee.co.id.sg5.tebel.cfd"
zone_name = "tebel.cfd"

[[routes]]
pattern = "sg5.tebel.cfd"
zone_name = "tebel.cfd"



[vars]
PROXYIP = "15.235.167.49"
DNS_NYA = "https://dns.adguard.com/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
