name = "my1"
main = "_workervli.js"
compatibility_date = "2023-05-26"


[[routes]] 
pattern = "shopee.co.id.my1.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "my1.freevpn.biz.id"
custom_domain = true


[vars]
PROXYIP = "103.75.188.126"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_NYA = "https://dns.google.com/dns-query"
