name = "sg1"
main = "_workervl.js"
compatibility_date = "2024-05-13"

[[routes]]
pattern = "sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "cache.netflix.com.sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "acces.iflix.com.sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.sg1.workers2.xyz"
custom_domain = true

[[routes]]
pattern = "*sg1.workers2.xyz/*"
zone_name = "workers2.xyz"

[vars]
PROXYIP = "128.199.228.44"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
