name = "test"
main = "_workervl.js"
compatibility_date = "2023-05-26"

[[routes]] 
pattern = "shopee.co.id.test.blondies.cfd"
custom_domain = true

[[routes]]
pattern = "test.blondies.cfd"
custom_domain = true

[[routes]]
pattern = "*.test.blondies.cfd"
zone_name ="blondies.cfd"


[vars]
PROXYIP = "128.199.228.44"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_RESOLVER_URL = "https://dns.google.com/dns-query"
