name = "id1"
main = "_workervl.js"
compatibility_date = "2024-05-13"

[[routes]]
pattern = "id1.porpuse.cfd"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.id1.porpuse.cfd"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.id1.porpuse.cfd"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.id1.porpuse.cfd"
custom_domain = true

[[routes]]
pattern = "*id1.porpuse.cfd/*"
zone_name = "porpuse.cfd"

[vars]
PROXYIP = "35.219.50.99"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
