name = "do"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]] 
pattern = "shopee.co.id.sg1.vapoor.cfd"
custom_domain = true

[[routes]]
pattern = "sg1.vapoor.cfd"
custom_domain = true





[vars]
PROXYIP = "128.199.228.44"
DNS_NYA = "https://dns.adguard.com/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
