name = "test"
main = "_workervl.js"
compatibility_date = "2023-05-26"


[[routes]] 
pattern = "shopee.co.id.test.freevpn.biz.id"
custom_domain = true

[[routes]]
pattern = "test.freevpn.biz.id"
custom_domain = true

workers_dev = true


[vars]
PROXYIP = "35.219.50.99"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_RESOLVER_URL = "https://dns.google.com/dns-query"
