name = "sg5" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "src/_worker-vless.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "sg5.dianastore.xyz"
custom_domain = true

[[routes]]
pattern = "shopee.co.id.sg5.dianastore.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa5"
PROXYIP = "52.74.101.26"
# DNS_RESOLVER_URL = "https://dns.google/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
