name = "apasi"
main = "src/_worker-vless.js"
compatibility_date = "2023-05-26"




[vars]
PROXYIP = "103.75.188.126"
DNS_NYA = "https://dns.google/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
