name = "sg1"
main = "_workervl.js"
compatible-date = "2024-02-12"

[[routes]]
pattern = "sg1.freevpn.biz.id"
custom_domain = true


[vars]
PROXYIP = "143.198.89.162"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
DNS_RESOLVER_URL = "https://dns.google.com/dns-query"
