name = "akr"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]] 
pattern = "shopee.co.id.sg3.vapoor.cfd"
custom_domain = true

[[routes]]
pattern = "sg3.vapoor.cfd"
custom_domain = true





[vars]
PROXYIP = "103.190.179.28"
DNS_NYA = "https://dns.adguard.com/dns-query"
UUID = "dfc3ad71-4ab8-424e-b5f7-965d18153ccb"
